project_name: opossum
builds:
  -
    id: "opossum"
    binary: "opossum"
    dir: cmd/opossum
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    vendor: Philip Silva
    homepage: https://github.com/psilva261/opossum
    maintainer: Philip Silva <psilva261@github.com>
    description: NA
    license: bsd
    formats:
      - apk
      - deb
      - rpm
    release: 1
    section: default
    priority: extra
